image: "python:3.8"

before_script:
  - eval "$(ssh-agent -s)"
    # Following: https://serverfault.com/questions/856194/securely-add-a-host-e-g-github-to-the-ssh-known-hosts-file
  - GITLAB_FINGERPRINT=$(ssh-keyscan -t ed25519 gitlab.com | tee gitlab-key-temp | ssh-keygen -lf -)
  - GITLAB_EXPECTED_FINGERPRINT="256 SHA256:eUXGGm1YGsMAS7vkcx6JOJdOGHPem5gQp4taiCfCLB8 gitlab.com (ED25519)"
  - if [ ! "$GITLAB_FINGERPRINT" = "$GITLAB_EXPECTED_FINGERPRINT" ]; then echo "Error - SSH fingerprint mismatch" 1>&2 && exit 25519; fi
  - mkdir -p ~/.ssh # This shouldn't be necessary but getting an error that "file/dir. doesn't exist" on next line
  - cat gitlab-key-temp >> ~/.ssh/known_hosts && rm gitlab-key-temp
  - ssh-add <(echo "${SSH_priv_key_GitLab}" | base64 --decode)
  - ssh-add <(echo "${SSH_priv_key_GitHub}" | base64 --decode)
  - git config --global user.email "${git_email}"
  - git config --global user.name "${full_name}"
  - python3.8 -m pip install -r requirements.txt

stages:
  - QL

quill:
  stage: QL
  script:
  - python3.8 -m pip install "ql"
  - python3.8 -c "import quill as ql; ql.source_manifest(); ql.fold.wire.standup(); ql.remote_push_manifest('Testing CI commit ability...')"
