image: "python:3.8"

before_script:
  - eval "$(ssh-agent -s)"
  - ssh-add - <(echo "${SSH_priv_key}" | base64 --decode)
  - git config --global user.email "${git_email}"
  - git config --global user.name "${full_name}"
  - python3.8 -m pip install -r requirements.txt

stages:
  - QL

quill:
  stage: QL
  script:
  - python3.8 -m pip install "ql"
  - python3.8 -c "import quill as ql; ql.source_manifest(); ql.fold.wire.standup(); ql.remote_push_manifest('Testing CI commit ability...')"
