__all__ = [
    "LAYOUT_DIRNAME",
    "LAYOUT_FILENAME",
    "OUT_DIRNAME",
    "POST_DIRNAME",
    "TEMPLATE_DIRNAME",
]

LAYOUT_DIRNAME = "layouts"
LAYOUT_FILENAME = "_post.html"
OUT_DIRNAME = "site"
POST_DIRNAME = "posts"
TEMPLATE_DIRNAME = "src"
